### ISSUE TITLE
parser not working when using npm run or yarn

### ISSUE THREAD

**Issue by tokra** [lpw/command-line-parser#1]
if you have defined package.json scripts eg. `start`
```
"scripts": {
    "start": "node src/main.js",
```
and when calling e.g.:
`yarn start -p 'paramValue'`

cmdline parser arguments are empty.

**Comment by lpw** [comment]
Thanks for raising the issue, sorry for the delay. 

This seems to be working for me.  Given the test program ```src/main.js```:
```
const argsObj = require('command-line-parser')();
console.log('TEST argsObj', argsObj);
```
run from package.json:
```
  "scripts": {
    "start": "node src/main.js"
  }
```
with the yarn command:
```
laptop-lpw$ yarn start -p 'paramValue'
```
gives these results:
```
yarn start v1.0.1
$ node src/main.js "-p" "paramValue"
TEST argsObj { p: 'paramValue' }
✨  Done in 0.19s.
laptop-lpw$
```
Perhaps I don't understand your expectations of running ```yarn``` with these options, or perhaps you are getting different results.

I notice it also works with ```npm```, although using ```--``` since ```npm``` will otherwise process the ```-p``` option instead of passing it along to the script as ```yarn``` does:
```
laptop-lpw$ npm start -- -p 'paramValue'

> test@1.0.0 start /Users/lpw/git/test
> node src/main.js "-p" "paramValue"

TEST argsObj { p: 'paramValue' }
laptop-lpw$
```
Let me know if you still see an issue here.
